# Travis CI configuration file.
language: php
php:
    - 7.0
    - 7.1

env:
  global:
    - MYSQL_HOSTNAME=localhost
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=scrum

notifications:
  email:
    recipients:
      - devci@j3ck3l.me
    on_success: change # default: change
    on_failure: always # default: always

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE scrum;'

before_script:
    # Start up a web server.
    #- php -S 127.0.0.1:8888 -t /path/to/web/root >/dev/null 2>&1 &
    # Start up the webdriver.
    #- phantomjs --webdriver=4444 >/dev/null 2>&1 &
    # Install Codeception.
    # Doing this last gives the webdriver and server time to start up.
    - composer install --prefer-source

script:
    - vendor/bin/codecept run --coverage-xml --env travis

after_script:
    - ./vendor/bin/coveralls
